"""Generate small, deterministic retrieval indexes from published notes only."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import yaml

from public_paths import public_note_path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_LINK = re.compile(r"timelines/(\d+)\.md")


def words(text: str) -> int:
    return len(re.findall(r"\b[\w'-]+\b", text))


def records() -> list[dict]:
    result = []
    for folder in ("canon", "session", "timelines"):
        for path in sorted((ROOT / "knowledge" / folder).rglob("*.md")):
            if path.name in {"README.md", "INDEX.md"}:
                continue
            relative = path.relative_to(ROOT).as_posix()
            safe_path = public_note_path(ROOT, relative, kind=folder)
            text = safe_path.read_text(encoding="utf-8")
            headings = re.findall(r"(?m)^# (.+)$", text)
            item = {"path": relative,
                    "title": headings[0] if headings else f"Clip {path.stem}",
                    "kind": folder, "words": words(text)}
            if folder == "canon":
                item["category"] = path.parent.name if path.parent.name != "canon" else "reference"
            if folder == "timelines":
                fm = yaml.safe_load(text.split("---", 2)[1])
                item.update(clip=str(fm["clip"]), day=str(fm["day"]),
                            module=fm["module"], duration=fm["duration"],
                            speakers=fm["speakers"])
            else:
                item["clips"] = sorted(set(SOURCE_LINK.findall(text)), key=int)
            result.append(item)
    return result


def outputs() -> dict[Path, str]:
    items = records()
    timeline = sorted((x for x in items if x["kind"] == "timelines"), key=lambda x: int(x["clip"]))
    data = {"schema_version": 1, "scope": "Grok Bot Galaxy, 2026-09-15 through 2026-09-17",
            "retrieval": "Use llms.txt and knowledge/ROUTES.md first; search.py returns bounded excerpts.",
            "documents": items}
    index = ["# Knowledge index", "", "<!-- Generated by scripts/build_catalog.py. -->", "",
             "Start with [task routes](ROUTES.md). Read one guide, then only the cited timeline blocks needed for evidence.", "",
             "All product descriptions are event observations from **15–17 September 2026**, not a current product specification.", ""]
    labels = {"explanation": "Understand the product", "tutorials": "Learn the basics",
              "how-to": "Task guides", "reference": "Reference and limits"}
    for category, label in labels.items():
        index.extend([f"## {label}", ""])
        for item in items:
            if item["kind"] == "canon" and item["category"] == category:
                index.append(f"- [{item['title']}]({item['path'].removeprefix('knowledge/')})")
        index.append("")
    index.extend(["## Event context", ""])
    for item in items:
        if item["kind"] == "session":
            index.append(f"- [{item['title']}]({item['path'].removeprefix('knowledge/')})")
    index.extend(["", "## Evidence and machine retrieval", "",
                  f"- [Timeline index](timelines/INDEX.md): {len(timeline)} recordings, with dates, modules and durations.",
                  "- [Catalog](catalog.json): paths, categories, source clips and word counts; no duplicated bodies.",
                  "- [Coverage]( _meta/coverage.yaml): machine extraction, alignment and canon-review status per clip.".replace("]( ", "]("),
                  "- [Evidence policy](_meta/evidence-policy.md) and [validation](../CONTRIBUTING.md).", ""])
    ti = ["# Timeline index", "", "<!-- Generated by scripts/build_catalog.py. -->", "",
          "Times in each file are relative to that clip. These are compressed aligned notes, not verbatim transcripts.",
          "Clips 030–042 are replay records; see [gaps and replay map](../session/gaps.md). Clip 047 transitions into the PM workshop.", ""]
    for day in sorted({x["day"] for x in timeline}):
        ti.extend([f"## {day}", "", "| Clip | Primary module | Duration |", "|---|---|---|"])
        for item in timeline:
            if item["day"] == day:
                ti.append(f"| [{item['clip']}]({item['clip']}.md) | {item['module']} | {item['duration']} |")
        ti.append("")
    return {ROOT / "knowledge/catalog.json": json.dumps(data, ensure_ascii=False, indent=2) + "\n",
            ROOT / "knowledge/INDEX.md": "\n".join(index),
            ROOT / "knowledge/timelines/INDEX.md": "\n".join(ti)}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    stale = []
    try:
        generated = outputs()
    except (OSError, ValueError, KeyError, TypeError, yaml.YAMLError) as exc:
        print(f"Catalog generation failed: {exc}", file=sys.stderr)
        return 1
    for path, content in generated.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print("Stale generated indexes: " + ", ".join(stale))
        return 1
    print("Retrieval indexes " + ("current" if args.check else "generated"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
